/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Miyuru.attendance;

import com.DB.Sales.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.Miyuru.login.SignIn;

/**
 *
 * @author miyuru_cg
 */
public class LeavesInterface extends javax.swing.JPanel {

    //Connection con;
    private Connection con;
    private String INSERT_SQL = "";
    boolean state = false;
    String[] val;
    
        
    
    
    /**
     * Creates new form LeavesInterface
     */
    public LeavesInterface() {
        initComponents();
        String[] value;
        
        if(SignIn.username.equals("Admin")){
            AcceptBtn.setEnabled(true);
            declineBtn.setEnabled(true);
        }else{
            AcceptBtn.setEnabled(false);
            declineBtn.setEnabled(false);
        }
        
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
        con = dbc.getConnection();
    }

    public void panelNavigator(JPanel panel){
        breaksLayer.removeAll();
        breaksLayer.add(panel);
        breaksLayer.repaint();
        breaksLayer.revalidate();
        //this.navbar.setText(name);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breaksLayer = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        start_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        end_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note_txt = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn3 = new javax.swing.JButton();
        AcceptBtn = new javax.swing.JButton();
        declineBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(28, 35, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breaksLayer.setLayout(new java.awt.CardLayout());

        jScrollPane2.setBackground(new java.awt.Color(28, 35, 51));

        jPanel1.setBackground(new java.awt.Color(28, 35, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attendance > Leaves");

        jPanel2.setBackground(new java.awt.Color(43, 54, 79));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee :");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Start Date :");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("End Date :");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Note :");

        note_txt.setColumns(20);
        note_txt.setRows(5);
        jScrollPane1.setViewportView(note_txt);

        addBtn.setBackground(new java.awt.Color(0, 153, 51));
        addBtn.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/Add_M.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        newBtn.setBackground(new java.awt.Color(0, 153, 153));
        newBtn.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        newBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/icons8-new-contact-30.png"))); // NOI18N
        newBtn.setText("New");
        newBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBtnMouseClicked(evt);
            }
        });
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(102, 102, 255));
        editBtn.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/Edit_m.png"))); // NOI18N
        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn3.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        deleteBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/Delete_m.png"))); // NOI18N
        deleteBtn3.setText("Delete");
        deleteBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtn3MouseClicked(evt);
            }
        });
        deleteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn3ActionPerformed(evt);
            }
        });

        AcceptBtn.setBackground(new java.awt.Color(0, 188, 61));
        AcceptBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/icons8-approval-30.png"))); // NOI18N
        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });

        declineBtn.setBackground(new java.awt.Color(255, 96, 96));
        declineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/icons8-unavailable-30.png"))); // NOI18N
        declineBtn.setText("Decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(start_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(495, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(emp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(emp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(start_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(end_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Start Date", "End Date", "Notes", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btn_back.setBackground(new java.awt.Color(0, 106, 78));
        btn_back.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/backW_32.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1760, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(307, 307, 307))
        );

        jScrollPane2.setViewportView(jPanel1);

        breaksLayer.add(jScrollPane2, "card2");

        add(breaksLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1621, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        AttendenceInterfave a = new AttendenceInterfave();

        panelNavigator(a);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        AttendenceInterfave a = new AttendenceInterfave();

        panelNavigator(a);
    }//GEN-LAST:event_btn_backActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:

        String start =start_txt.getText();
        String end = end_txt.getText();
        String empName = emp_txt.getText();
        String note = note_txt.getText();
        
        try{
           // for(Products product : products){
               PreparedStatement preparedStatement = con.prepareStatement("INSERT INTO emp_leaves (emp_name,startDate,endDate,note) values(?,?,?,?)");
        
               preparedStatement.setString(1, empName);          
               preparedStatement.setString(2, start);
               preparedStatement.setString(3, end);
               preparedStatement.setString(3, note);
               
               System.out.println(preparedStatement);
               
               int result = preparedStatement.executeUpdate();
               
               if(result > 0){
                   state = true;
               }else{
                   state = false;
               }
               setLeavesTableData();
            //}
        }catch(SQLException e){
            System.out.println(e);
        }
//        try{
//            Statement smt = con.createStatement();
//            smt.execute("INSERT INTO emp_leaves (emp_name,startDate,endDate,note) values('"+empName+"','"+start+"','"+end+"','"+note+"')");
//            JOptionPane.showMessageDialog(this, "Record Submitted");
//            setLeavesTableData();
//            smt.close();
//
//            /*
//
//            Statement smt = con.createStatement();
//            smt.execute("INSERT INTO sales(product_name,product_price,product_quantity,sales_value,tax,commision) values('"+productName+"','"+productPrice+"','"+productQuantity+"','"+salesValue+"','"+tax+"','"+commision+"')");
//            JOptionPane.showMessageDialog(this, "Record Submitted");
//            setSalesTableData();
//            getGrandTotal();
//            smt.close();
//
//            */
//
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(this, " error adding data >>> "+e);
//        }
        
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        model.addRow(new Object[]{emp_txt.getText(),start_txt.getText(),end_txt.getText(),note_txt.getText(),"Pending"});
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
//        // TODO add your handling code here:
//               String start =start_txt.getText();
//        String end = end_txt.getText();
//        String empName = emp_txt.getText();
//        String note = note_txt.getText();
//        
//        try{
//           // for(Products product : products){
//               PreparedStatement preparedStatement = con.prepareStatement("INSERT INTO emp_leaves (emp_name,startDate,endDate,note) values(?,?,?,?)");
//        
//               preparedStatement.setString(1, empName);          
//               preparedStatement.setString(2, start);
//               preparedStatement.setString(3, end);
//               preparedStatement.setString(3, note);
//               
//               System.out.println(preparedStatement);
//               
//               int result = preparedStatement.executeUpdate();
//               
//               if(result > 0){
//                   state = true;
//               }else{
//                   state = false;
//               }
//               setLeavesTableData();
//            //}
//        }catch(SQLException e){
//            System.out.println(e);
//        }
////        try{
////            Statement smt = con.createStatement();
////            smt.execute("INSERT INTO emp_leaves (emp_name,startDate,endDate,note) values('"+empName+"','"+start+"','"+end+"','"+note+"')");
////            JOptionPane.showMessageDialog(this, "Record Submitted");
////            setLeavesTableData();
////            smt.close();
////
////            /*
////
////            Statement smt = con.createStatement();
////            smt.execute("INSERT INTO sales(product_name,product_price,product_quantity,sales_value,tax,commision) values('"+productName+"','"+productPrice+"','"+productQuantity+"','"+salesValue+"','"+tax+"','"+commision+"')");
////            JOptionPane.showMessageDialog(this, "Record Submitted");
////            setSalesTableData();
////            getGrandTotal();
////            smt.close();
////
////            */
////
////        }catch(Exception e){
////            JOptionPane.showMessageDialog(this, " error adding data >>> "+e);
////        }
//        
//        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
//
//        model.addRow(new Object[]{emp_txt.getText(),start_txt.getText(),end_txt.getText(),note_txt.getTabSize()});
    }//GEN-LAST:event_addBtnActionPerformed

    private void newBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtnMouseClicked
        emp_txt.setText(null);
        start_txt.setText(null);
        end_txt.setText(null);
        note_txt.setText(null);
    }//GEN-LAST:event_newBtnMouseClicked

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        if(jTable2.getSelectedRow()== -1){
            if(jTable2.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is empty !");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row !");
            }
        }else{
            model.setValueAt(emp_txt.getText(), jTable2.getSelectedRow(), 0);
            model.setValueAt(start_txt.getText(), jTable2.getSelectedRow(), 1);
            model.setValueAt(end_txt.getText(), jTable2.getSelectedRow(), 2);
            model.setValueAt(note_txt.getText(), jTable2.getSelectedRow(), 2);

            JOptionPane.showMessageDialog(this, "Data Edited Successfully !");
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed

    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtn3MouseClicked

    private void deleteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        if (jTable2.getSelectedRow() == -1) {
            if(jTable2.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is empty !");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row!");
            }
        }
        else{
            model.removeRow(jTable2.getSelectedRow());

        }
    }//GEN-LAST:event_deleteBtn3ActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        if(jTable2.getSelectedRow()== -1){
            if(jTable2.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is empty !");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row !");
            }
        }else{

            model.setValueAt("Accept", jTable2.getSelectedRow(), 4);

            JOptionPane.showMessageDialog(this, "Accepted");
        }
        
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();

        if(jTable2.getSelectedRow()== -1){
            if(jTable2.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is empty !");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row !");
            }
        }else{

            model.setValueAt("Decline", jTable2.getSelectedRow(), 4);

            JOptionPane.showMessageDialog(this, "Declined");
        }
    }//GEN-LAST:event_declineBtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        
        if(jTable2.getSelectedRow()== -1){
            if(jTable2.getRowCount()== 0){
                JOptionPane.showMessageDialog(this, "Table is empty !");
            }else{
                JOptionPane.showMessageDialog(this, "Please select a row !");
            }
        }else{
            emp_txt.setText((String) jTable2.getValueAt(jTable2.getSelectedRow(), 0));
            start_txt.setText((String) jTable2.getValueAt(jTable2.getSelectedRow(), 1));
            end_txt.setText((String) jTable2.getValueAt(jTable2.getSelectedRow(), 2));
            note_txt.setText((String) jTable2.getValueAt(jTable2.getSelectedRow(), 3));


        }

    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLayeredPane breaksLayer;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton declineBtn;
    private javax.swing.JButton deleteBtn3;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField emp_txt;
    private javax.swing.JTextField end_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextArea note_txt;
    private javax.swing.JTextField start_txt;
    // End of variables declaration//GEN-END:variables

    private void setLeavesTableData() {
        try{
            int rows = 0;
            int rowIndex = 0;
            try (Statement smt = con.createStatement(); ResultSet rs = smt.executeQuery("SELECT * FROM emp_leaves")) {
                if(rs.next()){
                    rs.last();
                    rows = rs.getRow();
                    rs.beforeFirst();
                }
                String[][] data = new String[rows][4];
                while(rs.next()){
                    data[rowIndex][0]=rs.getString(1)+"";
                    data[rowIndex][1]=rs.getString(2);
                    data[rowIndex][2]=rs.getString(3);
                    data[rowIndex][3]=rs.getString(4)+"";
                    
                    rowIndex++;
                }
                String[] cols={"Employee","Start Date","End Date","Notes"};
                DefaultTableModel model = new DefaultTableModel(data,cols);
                jTable2.setModel(model);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e +" Retreiving Failed");
        }

    }
}
